### ISSUE TITLE
Netflix is not working anymore

### ISSUE THREAD

**Issue by grosseskino** [TBSniller/piccap#38]
Hi.

Netflix is not working anymore after the netflix app was updated.
Hyperion is receiving a black image.

Any ideas how I can fix this?

**Comment by TBSniller** [comment]
Hey thats indeed quite intresting. Can you please post output of `grep -h -E '"(hardware_id|core_os_release|product_id|webos_manufacturing_version|board_type)"' /var/run/nyx/*`

**Comment by TBSniller** [comment]
Crazy that it even was possible for you. I have the same TV at home and receiving DRM protected content like from Netflix was never possible for me. That what's happening for you now, is sadly what's expected for TVs after 2020.

**Comment by grosseskino** [comment]
That's weird..
I thought the screen capture in general was not affected by drm content..?
Is there another driver that would work for newer tvs'?
I read in the hyperion-webos that it depends on the tv and firmware..

**Comment by kafisc1** [comment]
Are there any news regarding this issue?
Thank's in advance

**Comment by EyalRotem** [comment]
> Sadly there isn't.
> But this weekend I have made a huge progress regarding this for our TVs. Hit me up on discord, we can test something.

May I ask what progress? 
I have a CX and it seems similar in webos version

**Comment by TBSniller** [comment]
Due to potential legal issues and also because we don't want to risk any regulations from LG for the OpenLG-Community, we have decieded to stop any further proccess regarding this. 
I've tried to contact some persons from LG and hoped they can create some capture interface for DRM content for us, but sadly they only have answered with some default stuff.. Maybe in some time this project gets bigger and LG sees that there are lots of people buying LG TVs because of native capture, so they do it for us. But until then only this applies:

```
On newer TVs there is no official way for capturing DRM-protected content like from Netflix or Amazon. This restriction doesn't take place for content comming from an HDMI input.
So currently as a workaround you can play your media using your PC, FireTV-Stick or Chromecast and still enjoy your LEDs.
```
